import { CONTAINER, CONTAINER_365, DASHBOARD_LISTING, LOGIN_REFRESH, POST, SELECT, SIDE_MENU_365, SLIDER } from "../../components/utils/Const";

const HEADER = {
  type: CONTAINER_365,
  className: "homeHeader",

  children: [
    {
      type: "PAGE_HEADER",
      url: "/",
      image: "Sales> Allocated Leads",
      title: "Sales> Allocated Leads",
      titleMobile: "Sales> Allocated Leads",
      className: "page_header_comp",
    },
    {
      dataKey: "data_Key",
      label: "searchHere",
      name: "searchHere",
      icon: "search",
      requiredErrorMessage: "",
      type: "TEXT_INPUT",
    },
    {
      name: "Notification",
      label: "notification",
      icon: " bell_notification",
      dataKey: "text",
      type: "click",
      isRequired: " True",
      requiredErrorMessage: ".",
    },
    {
      name: "user_profile",
      label: "User",
      icon: " user-icon",
      dataKey: "text",
      type: "click",
      isRequired: " True",
      requiredErrorMessage: ".",
    },
  ],
};

//menu item of sidebar
const MENU_ITEMS = [
  {
    name: "Home",
    path: "/",
    icon: "HOME_logo",
  },
  {
    name: "Dashboard",
    path: "/Dashboard",
    icon: "Dashboard",
  },
  {
    name: "Sales",
    path: "/Sales",
    icon: "Sales",
  },
  {
    name: "Calls",
    path: "/Calls",
    icon: "Calls",
  },
  {
    name: "Indicators",
    path: "/Indicators",
    icon: "Indicators",
  },
  {
    name: "Team Manager",
    path: "/Team Manager",
    icon: "Team Manager",
  },
];

export const QA_EXECUTIVE_CLOSE_CALL_ALLOCATED_CALL_SCREEN = {
  name: "close_call_allocated_call_screen",
  children: [
    HEADER,
    {
      type: SIDE_MENU_365,
      items: MENU_ITEMS,
      className: "menu_comp",
      text: "Menu",
    },

    {
      type: "CONTAINER",
      name: "allocated calls",
      children: [
        {
          type: SELECT,
          className: "select-filter-button",
          sliceName: "filter",
          name: "Product/Service",
          defaultValue: { label: "Product A", value: "Product b" },
          options: [{ label: "Product A", value: "Product b" }],
          onClickApi: "API_ENDPOINTS[GET_SEARCH_RESULT]",
          onClickApiMethod: "POST",
        },
        {
          type: SELECT,
          className: "select-call-disposition-button",
          sliceName: "filter",
          name: "Call Disposition",
          defaultValue: {
            label: "Follow-up required",
            value: "followUp",
          },
          options: [{ label: "Follow-up required", value: "followUp" }],
          onClickApi: "API_ENDPOINTS[GET_SEARCH_RESULT]",
          onClickApiMethod: "POST",
        },
        {
          type: SELECT,
          className: "select-call-type-button",
          sliceName: "filter",
          name: "Call Type",
          defaultValue: { label: "Product Demo", value: "productDemo" },
          options: [{ label: "Product Demo", value: "productDemo" }],
          onClickApi: "API_ENDPOINTS[GET_SEARCH_RESULT]",
          onClickApiMethod: "POST",
        },

        {
          type: SLIDER,
          sliceName: "filter",
          className: "select-range",
          name: "Call Duration",
          minValue: 30,
          maxValue: 60,
          defaultValue: 30,
        },
        {
          type: SLIDER,
          sliceName: "filter",
          className: "select-range",
          name: "Call Score",
          minValue: 0,
          maxValue: 100,
          defaultValue: 0,
        },
        // two dates to be added
        {
          type: SELECT,
          className: "select-review-button",
          sliceName: "filter",
          name: "On Time Review",
          defaultValue: { label: "No", value: "no" },
          options: [{ label: "No", value: "no" }],
          onClickApi: "API_ENDPOINTS[GET_SEARCH_RESULT]",
          onClickApiMethod: "POST",
        },
        {
          type: SELECT,
          className: "select-delay-time-button",
          sliceName: "filter",
          name: "Delay TIme",
          defaultValue: { label: "2 days", value: "2" },
          options: [{ label: "2 days", value: "2" }],
          onClickApi: "API_ENDPOINTS[GET_SEARCH_RESULT]",
          onClickApiMethod: "POST",
        },
        {
          type: SELECT,
          className: "select-review-button",
          sliceName: "filter",
          name: "Time to complete review",
          defaultValue: { label: "5 days", value: "5" },
          options: [{ label: "5 days", value: "5" }],
          onClickApi: "API_ENDPOINTS[GET_SEARCH_RESULT]",
          onClickApiMethod: "POST",
        },
        {
          type: LOGIN_REFRESH,
          name: "",
          className: "",
          children: [
            {
              type: CONTAINER,
              name: "",
              className: "",
              children: [
                {
                  type: DASHBOARD_LISTING,
                  data: {},
                  desktopHeaders: {
                    "Call ID": "callId",
                    "Call Title": "callTitle",
                    "Lead Id": "leadId",
                    "Lead Title": "leadTitle",
                    Participants: "participants",
                    "Call Owner": "callOwner",
                    "Team Manager": "teamManager",
                    "Client POC": "clientPOC",
                    "Company Name": "companyName",
                    "Call Date And Time": "callDateTime",
                    "Product/Service": "productOrService",
                    "Call Duration": "callDuration",
                    "Call Disposition": "callDisposition",
                    "Call Type": "callType",
                    "Call Score": "callScore",
                    "Call Review Type": "callReviewType",
                    "Call Review Status": "callReviewStatus",
                    "Close Date": "closeDate",
                    "Allocated On": "allocatedOn",
                    "Review Due Date": "reviewDueDate",
                    "Last Updated On": "lastUpdatedOn",
                    "On Time Review": "onTimeReview",
                    "Delay Time": "delayTime",
                    "Time to complete review": "timeToCompleteReview",
                  },
                  mobileHeaders: {
                    "Call ID": "callId",
                    "Call Title": "callTitle",
                    "Lead Id": "leadId",
                    "Lead Title": "leadTitle",
                    Participants: "participants",
                    "Call Owner": "callOwner",
                    "Team Manager": "teamManager",
                    "Client POC": "clientPOC",
                    "Company Name": "companyName",
                    "Call Date And Time": "callDateTime",
                    "Product/Service": "productOrService",
                    "Call Duration": "callDuration",
                    "Call Disposition": "callDisposition",
                    "Call Type": "callType",
                    "Call Score": "callScore",
                    "Call Review Type": "callReviewType",
                    "Call Review Statys": "callReviewStatus",
                    "Close Date": "closeDate",
                    "Allocated On": "allocatedOn",
                    "Review Due Date": "reviewDueDate",
                    "Last Updated On": "lastUpdatedOn",
                    "On Time Review": "onTimeReview",
                    "Delay Time": "delayTime",
                    "Time to complete review": "timeToCompleteReview",
                  },

                  fieldConst: "newPropertyConst",
                  editApi: "ALTER_CLOSE_CALL_ALLOCATED_CALL_DATA",
                  deleteApi: "DELETE_CLOSE_CALL_ALLOCATED_CALL_DATA",
                  getDataApi: "GET_CLOSE_CALL_ALLOCATED_CALL",
                  approveApi: "APPROVE_CLOSE_CALL_ALLOCATED_CALL_DATA",
                  endpoint: "API_ENDPOINTS[GET_CLOSE_CALL_ALLOCATED_CALL]",
                  dataPoint: "GET_CLOSE_CALL_ALLOCATED_CALL",
                  onRefreshApiType: POST,
                  disableRowModal: true,
                  showPreviewButton: true,
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};

export const QA_EXECUTIVE_CLOSE_CALL_FEEDBACK_CALL_SCREEN = {
  name: "close_call_feedback_call_screen",
  children: [
    HEADER,
    {
      type: SIDE_MENU_365,
      items: MENU_ITEMS,
      className: "menu_comp",
      text: "Menu",
    },
    {
      type: "CONTAINER",
      name: "allocated calls",
      children: [
        {
          type: SELECT,
          className: "select-filter-button",
          sliceName: "filter",
          name: "Product/Service",
          defaultValue: { label: "Product A", value: "Product b" },
          options: [{ label: "Product A", value: "Product b" }],
          onClickApi: "API_ENDPOINTS[GET_SEARCH_RESULT]",
          onClickApiMethod: "POST",
        },
        {
          type: SELECT,
          className: "select-call-disposition-button",
          sliceName: "filter",
          name: "Call Disposition",
          defaultValue: {
            label: "Follow-up required",
            value: "followUp",
          },
          options: [{ label: "Follow-up required", value: "followUp" }],
          onClickApi: "API_ENDPOINTS[GET_SEARCH_RESULT]",
          onClickApiMethod: "POST",
        },
        {
          type: SELECT,
          className: "select-call-type-button",
          sliceName: "filter",
          name: "Call Type",
          defaultValue: { label: "Product Demo", value: "productDemo" },
          options: [{ label: "Product Demo", value: "productDemo" }],
          onClickApi: "API_ENDPOINTS[GET_SEARCH_RESULT]",
          onClickApiMethod: "POST",
        },

        {
          type: SLIDER,
          sliceName: "filter",
          className: "select-range",
          name: "Call Duration",
          minValue: 30,
          maxValue: 60,
          defaultValue: 30,
        },
        // two dates

        {
          type: LOGIN_REFRESH,
          name: "",
          className: "",
          children: [
            {
              type: CONTAINER,
              name: "",
              className: "",
              children: [
                {
                  type: DASHBOARD_LISTING,
                  data: {},
                  desktopHeaders: {
                    "Call ID": "callId",
                    "Call Title": "callTitle",
                    "Lead Id": "leadId",
                    "Lead Title": "leadTitle",
                    Participants: "participants",
                    "Call Owner": "callOwner",
                    "Team Manager": "teamManager",
                    "Client POC": "clientPOC",
                    "Company Name": "companyName",
                    "Call Date And Time": "callDateTime",
                    "Product/Service": "productOrService",
                    "Call Duration": "callDuration",
                    "Call Disposition": "callDisposition",
                    "Call Type": "callType",
                    "Call Score": "callScore",
                    "Call Review Type": "callReviewType",
                    "Call Review Status": "callReviewStatus",
                    "Close Date": "closeDate",
                    "Allocated On": "allocatedOn",
                    "Review Due Date": "reviewDueDate",
                    "Last Updated On": "lastUpdatedOn",
                    "Feedback Requested On": "feedbackRequestedOn",
                    "On Time Review": "onTimeReview",
                    "Delay Time": "delayTime",
                    "Time to complete review": "timeToCompleteReview",
                  },
                  mobileHeaders: {
                    "Call ID": "callId",
                    "Call Title": "callTitle",
                    "Lead Id": "leadId",
                    "Lead Title": "leadTitle",
                    Participants: "participants",
                    "Call Owner": "callOwner",
                    "Team Manager": "teamManager",
                    "Client POC": "clientPOC",
                    "Company Name": "companyName",
                    "Call Date And Time": "callDateTime",
                    "Product/Service": "productOrService",
                    "Call Duration": "callDuration",
                    "Call Disposition": "callDisposition",
                    "Call Type": "callType",
                    "Call Score": "callScore",
                    "Call Review Type": "callReviewType",
                    "Call Review Statys": "callReviewStatus",
                    "Close Date": "closeDate",
                    "Allocated On": "allocatedOn",
                    "Review Due Date": "reviewDueDate",
                    "Last Updated On": "lastUpdatedOn",
                    "Feedback Requested On": "feedbackRequestedOn",
                    "On Time Review": "onTimeReview",
                    "Delay Time": "delayTime",
                    "Time to complete review": "timeToCompleteReview",
                  },

                  fieldConst: "newPropertyConst",
                  editApi: "ALTER_CLOSE_CALL_FEEDBACK_CALL_DATA",
                  deleteApi: "DELETE_CLOSE_CALL_FEEDBACK_CALL_DATA",
                  getDataApi: "GET_CLOSE_CALL_FEEDBACK_CALL",
                  approveApi: "APPROVE_CLOSE_CALL_FEEDBACK_CALL_DATA",
                  endpoint: "API_ENDPOINTS[GET_CLOSE_CALL_FEEDBACK_CALL]",
                  dataPoint: "GET_CLOSE_CALL_FEEDBACK_CALL",
                  onRefreshApiType: POST,
                  disableRowModal: true,
                  showPreviewButton: true,
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
